### ISSUE TITLE
is there a way to sort by relevance?

### ISSUE THREAD

**Issue by captainbboy** [talmobi/yt-search#19]
i think the bot is sorting by views because I put in a specific title and it didn't show up (small # of views).  can I sort by relevance? or does it just use youtube's search with no filters?

**Comment by talmobi** [comment]
Videos with less than 5 views was being wrongfully discriminated against (putting them at the bottom of the list). This has been fixed in v2.1.7

`npm install yt-search@2.1.7`

**Comment by captainbboy** [comment]
the videos i'm looking up have like 1000+ views, but they still don't appear. (Searching for "Pollitos Raids Karma | Minecraft Factions Raid Edit", "Pollitos Raids Joker | Minecraft Factions Edit") which appear first when I look it up, but even when I search it up in youtube and put sort by view, it still shows up, so I am unsure why I am getting the options:
1 - 764141 | Increiible!!! Pollitos jugando al rugby! (1:17) | Mauricio Valenti
2 - 3385765 | pollitos naciendo con la gallina !! INCREIBLE !! (2:21) | GL 100
3 - 822600904 | El Pollito Pío 3D - Canciones de la Granja de Zenón 2 (3:08) | El Reino Infantil
4 - 1502719 | Canticos | 1 hora con los pollitos Ricky, Nicky y Kiki | Canciones infantiles | Aprende inglés (54:59) | Canticos - Bilingual Nursery Rhymes & Kids Songs
5 - 1340498275 | PULCINO PIO - El Pollito Pio (Official video) (2:47) | PULCINO PIO

**Comment by talmobi** [comment]
YouTube may be serving you specifically based on your search history. Try comparing the results with results you get when searching from an Incognito browser session.

**Comment by captainbboy** [comment]
I did, it still says the correct video in the incognito tab.

**Comment by talmobi** [comment]
Perhaps the 'accept-language': 'en-US' header being sent from your browser is different than the default that yt-search usess. You can check the network tab from your devtools to see which headers, specifically the 'accept-language' header, is being sent and post them here.

**Comment by talmobi** [comment]
Any updates on this? Did you get it resolved?

`yt-search` does not alter the order in which youtube serves up the results. However, `yt-search` defaults to the `accept-language: en-US` header which might alter the search results if you are using youtube with a different language than English. There is currently no options to set in `yt-search` to change the `accept-language` header to be something else than `en-US`, maybe it should be added?

**Comment by talmobi** [comment]
closing as inactive
